### ISSUE TITLE
#1 to-do 

### ISSUE THREAD

**Issue by slothly** [slothly/Apollo#1]
- [ ] incorporate animation into splash screen
- [ ] make the navigation more consistent
- [ ] smoothen the animations 
- [ ] integrate music streaming prototype
- [ ] create walk-through of the app to explain what it is and what you can do and why it's awesome :+1: 
- [ ] re-order the main menu contents (in order from top to bottom: search, music discovery, recently played, then your top played music divided into three subcategories: songs, albums, and artists
